- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/dto/PostDetailDto.java
- src/main/java/com/studycollaboproject/scope/service/ApplicantService.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- updateStatus - user 여부 판단 예외처리 추가
- editPost - user 여부 판단 예외처리 추가
- deletePost - user 여부 판단 예외처리 추가
- readPost - user 여부 판단 예외처리 추가
> [수정] post 예외처리 추가

- src/main/java/com/studycollaboproject/scope/dto/MypagePostListDto.java
- src/main/java/com/studycollaboproject/scope/dto/MypageResponseDto.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
마이페이지에서 쓰이는 List<Post>를 List<RequestPostDto>로 수정했습니다!
> [수정] 마이페이지 조회 수정

- src/main/java/com/studycollaboproject/scope/dto/MypageResponseDto.java
- src/main/java/com/studycollaboproject/scope/dto/PostDetailDto.java
- src/main/java/com/studycollaboproject/scope/dto/UserResponseDto.java
> [추가] 스웨거 추가

- src/main/java/com/studycollaboproject/scope/dto/PostRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
Post 객체 안에  isBookmarkChecked여부가 있으면 한 포스트에 여러 유저가 연관되어 있기 때문에 반환 시 PostResponseDto 인스턴스안에 체크 여부를 포함하여 넘겨주었습니다.
PostRequestDto 내의 북마크 리스트는 사용하지 않는 부분이므로 삭제하였습니다.
-  isBookmarkChecked 전체 불러오기 추가 / PostRequestDto 테이블 수정
-
> [추가] isBookmarkChecked 전체 불러오기 추가 / PostRequestDto 테이블 수정

- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
- src/main/java/com/studycollaboproject/scope/controller/ImageRestController.java
Image 파일을 저장하고 해당 resource Url을 전달 할 수 있는 API 추가
- ImageRestController 추가 및 API 추가
- WebConfig 파일에 addResourceHandler로 경로 설정 
- 파일 삭제는 직접 해야합니다
> [추가] Image Controller 추가

- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
- src/main/java/com/studycollaboproject/scope/controller/ImageRestController.java
- src/main/java/com/studycollaboproject/scope/exception/ErrorCode.java
Image 저장 경로 수정
- ImageController 메서드 명 변경
- api requestBody부분 변경
- 파일 저장 경로 변경
-
> [수정] Image Controller 수정

- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
TestDataRunner 수정
- TestDataRunner에 db가 비어있는지 판단하는 if문 추가
-
> [수정] TestDataRunner 수정

- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
- src/main/java/com/studycollaboproject/scope/dto/SignupTestDto.java
- src/main/java/com/studycollaboproject/scope/model/User.java
ApiTestRestController에서 SignupTestDto로 값 받게 수정
- test용 SignupTestDto 추가
- [ApiTestController] makeApiTestUser에서 인자값 signupDto로 변경
-
> [수정] ApiTestRestController에서 SignupTestDto로 값 받게 수정

- src/main/java/com/studycollaboproject/scope/controller/ApplicantRestController.java
- src/main/java/com/studycollaboproject/scope/controller/AssessmentRestController.java
- src/main/java/com/studycollaboproject/scope/controller/ImageRestController.java
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/SnsLoginRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/dto/ApplicantRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/AssessmentRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/ImageRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/ProjectStatusRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/PropensityRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/TeamRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/UrlUpdateRequestDto.java
ModelAttribute로 받을 시, 데이터가 들어오지 않는 문제가 있어서 모두 dto로 변경
- @ModelAttribute -> DTO로 변경
-
> [수정] ModelAttribute -> DTO 로 변경

- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
수정 및 작성 작업 시 결과 출력
- response data 영역에 해당 정보를 출력할 수 있도록 수정
-
> [수정] 수정 및 작성 작업 시 결과 출력

- src/main/java/com/studycollaboproject/scope/dto/PostRequestDto.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- post작성시 list형태로 techStack을 입력받아 저장하도록 수정하였습니다.
- PostRequestDto에  techStackList를 추가하여 스트링 대신 리스트로 받을 수 있도록 하였습니다.
- writePost에서 getTechStack을 convertStringToTechStack에 파라메터로 입력하였습니다.
-
> [수정] post작성시 list형태로 techStack 입력받아 저장

- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/dto/PostRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/SignupTestDto.java
테스트 회원가입 문제, 게시글 작성 시 startDate, endDate 저장안되는 문제 해결
- PostRequestDto 수정
- SignupTestDto 수정
-
> [수정] 게시글 작성 기능 수정

- src/main/java/com/studycollaboproject/scope/controller/TestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/dto/SignupRequestDto.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
userController에 값 변경 요청을 하는 user가 본인의 정보를 요청하는 지 판단하는 로직 추가
- url 변경 ({userId 추가})
- userDetails -> userDetailsImpl로 변경 
- user 본인의 정보를 수정하려고 하는지 판단하는 로직 추가
-
> [수정] userController에 값 변경 요청을 하는 user가 본인의 정보를 요청하는 지 판단하는 로직 추가

- src/main/java/com/studycollaboproject/scope/dto/PostRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/exception/ErrorCode.java
- src/main/java/com/studycollaboproject/scope/exception/RestApiExceptionHandler.java
게시글 작성시 값이 없을 때 처리 구문 추가
- errorException 추가
- PostRequestDto 기술스택 중복 제거
-
> [수정] 게시글 작성 시 null 인경우 처리

- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/exception/RestApiExceptionHandler.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
- src/main/java/com/studycollaboproject/scope/model/TechStack.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
- src/main/java/com/studycollaboproject/scope/util/TechStackConverter.java
게시글 조회시 기술 스택이 출력되지 않음.
- 기술 스택을 게시글에도 저장되도록 변경
-
> [수정] 게시글 조회 수정

- src/main/java/com/studycollaboproject/scope/controller/ServerRestController.java
- 현재 어떤 포트를 사용하고 있는지 확인하는 API (임시)
- 쉘 스크립트이용하여 포트 전환하기 위한 포트 확인
- ex) java -jar -Dspring.profiles.active={real1} *.jar
- 괄호 안에 있는 설정값 확인하여 포트 확인
-
> [추가] 현재 어떤 포트를 사용하고 있는지 확인하는 API (임시)

- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/dto/MemberListResponseDto.java
- src/main/java/com/studycollaboproject/scope/dto/ProjectStatusRequestDto.java
comment 오타 수정, 기타 오류 수정
- unknown 객체 만들 때 에러 수정
- 로그인 사용자가 아닐때 프로젝트 상세정보를 요청시 에러 수정
-
> [수정] 오타 수정, 에러 수정

- src/main/java/com/studycollaboproject/scope/controller/AssessmentRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestRestController.java
- src/main/java/com/studycollaboproject/scope/dto/MemberListResponseDto.java
- src/main/java/com/studycollaboproject/scope/exception/ErrorCode.java
- src/main/java/com/studycollaboproject/scope/model/Team.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
팀원평가 예외처리 추가
- AssessmentService에서 팀원 평가시 자기 자신은 평가할 수 없게 변경
-
> [수정] 팀원 평가시 자기 자신은 평가할 수 없게 변경

- src/main/java/com/studycollaboproject/scope/controller/SnsLoginRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/dto/SignupTestDto.java
- src/main/java/com/studycollaboproject/scope/dto/SnsInfoDto.java
- src/main/java/com/studycollaboproject/scope/service/GithubUserService.java
- src/main/java/com/studycollaboproject/scope/service/KakaoUserService.java
- src/main/java/com/studycollaboproject/scope/service/NaverUserService.java
- src/main/java/com/studycollaboproject/scope/service/TestService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
- src/main/java/com/studycollaboproject/scope/util/TechStackConverter.java
게시글, 유저 더미 데이터 추가
회원가입 에러 수정
회원가입 ID 변경
- TestDataRunner 코드에 더미 데이터 추가 로직 추가
- Map.get(key) 시 key값이 없는 경우를 처리
- SnsId를 SNS의 앞글자를 붙여서 처리 Github -> G-ID, Kakao -> K-ID, Naver -> N-ID
-
> [추가] 더미 데이터 추가

- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/repository/BookmarkRepository.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepository.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
[수정] Post filter 수정/ display 메소드 생성 / recommend, bookmark 분리
- Post filter부분 로직 수정, sendByDisplayNumber  메소드 생성/ recommend, bookmark 분리
-
> [수정] Post filter 수정/ display 메소드 생성 / recommend, bookmark 분리

- build.gradle
- src/main/java/com/studycollaboproject/scope/controller/ApplicantRestController.java
- src/main/java/com/studycollaboproject/scope/controller/AssessmentRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/dto/MailDto.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
- src/main/java/com/studycollaboproject/scope/service/MailService.java
- src/main/java/com/studycollaboproject/scope/service/TeamService.java
메일 알림 로직 구현
- 팀원 신청시 게시자에게 알림
- 게시자가 팀원 승인시 팀원에게 알림
- 프로젝트가 종료되었을 때 팀원들에게 알림
-
> [추가] 메일 알림 로직 구현

- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/exception/RestApiExceptionHandler.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
Post Read 정렬 순서 변경
swagger 수정
- swagger allowEmptyValue=true 수정
- Post Read 정렬 순서 내림차순으로 변경
-
> [수정] Post Read 정렬 순서 변경, swagger 수정

- src/main/java/com/studycollaboproject/scope/model/Tech.java
- src/main/java/com/studycollaboproject/scope/model/User.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepository.java
- src/main/java/com/studycollaboproject/scope/repository/TechStackRepository.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/util/TechStackConverter.java
테크 스택 수정, 추천 프로젝트 필터링 추가
- 테크스택 angular, react native 제외
- 테크스택 C++ -> cpp, PHP -> php, Node.js -> Node
-
> [수정] 테크 스택 수정, 추천 프로젝트 필터링 추가

- .github/workflows/gradle.yml
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
EC2연동을 위한 gradle.yml S3 버킷으로 전달
- WORKFLOW 수정
-
> [생성] EC2연동을 위한 ZIP파일 S3 버킷으로 전달

- .github/workflows/gradle.yml
[생성] S3버킷 -> EC2 인스턴스 WORKFLOW 생성
- [생성] S3버킷 -> EC2 인스턴스 WORKFLOW 생성
-
> [생성] S3버킷 -> EC2 인스턴스 WORKFLOW 생성

- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/model/User.java
- src/main/java/com/studycollaboproject/scope/service/MailService.java
- src/main/resources/templates/applicantEmail.html
- src/main/resources/templates/applicationNoticeEmail.html
- src/main/resources/templates/emailAuthentication.html
메일 알림 테스트 후 수정
- TeamRestController.java msg수정
- TestDataRunner.java 토큰 추가
- User.java 토큰 추가
- MailService.java html 경로 수정
- applicantEmail.html title 추가
- emailAuthentication.html <span>위치 변경
- applicationNoticeEmail.html  <span>위치 변경
- emailAuthentication.html   <span>위치 변경
-
> [수정] 메일 알림 테스트 후 수정

- build.gradle
- src/main/java/com/studycollaboproject/scope/ScopeApplication.java
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
- src/main/java/com/studycollaboproject/scope/model/User.java
- src/main/java/com/studycollaboproject/scope/repository/BookmarkRepository.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepository.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/util/TechStackConverter.java
- src/test/java/com/studycollaboproject/scope/integration/PostIntegrationTest.java
- src/test/java/com/studycollaboproject/scope/integration/TeamIntegrationTest.java
- src/test/java/com/studycollaboproject/scope/integration/UserIntegrationTest.java
- src/test/resources/application-dev.properties
querydsl 적용
- 게시물 조회 querydsl 적용
-
> [수정] 게시물 조회 query 최적화

- .github/workflows/gradle.yml
- appspec.yml
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
[추가] 포스트 반환 시 totalpage추가
-  [추가] 포스트 반환 시 totalpage추가
-
> [추가] 포스트 반환 시 totalpage추가

- .github/workflows/gradle.yml
[추가] appspec.yml Copy workflow 추가
- [추가] appspec.yml Copy workflow 추가
-
> [추가] appspec.yml Copy workflow 추가

- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepository.java
- src/main/java/com/studycollaboproject/scope/service/TeamService.java
- 팀원 강퇴 기능 추가 
- 팀 탈퇴 기능 추가
- 팀원 강퇴 기능 추가 
- 팀 탈퇴 기능 추가
> [추가] 팀원 강퇴, 팀 탈퇴 기능 추가

- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
- src/main/java/com/studycollaboproject/scope/config/WebSecurityConfig.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/dto/MypagePostListDto.java
- src/main/java/com/studycollaboproject/scope/filter/LogFilter.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepository.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/security/ExceptionHandlerFilter.java
- src/main/java/com/studycollaboproject/scope/security/JwtAuthenticationFilter.java
- src/main/java/com/studycollaboproject/scope/security/JwtTokenProvider.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
filter 순서 지정, 마이페이지 query 최적화
- WebConfig 파일 수정
- getMyPostList 수정
-
> [수정] filter 순서 수정

- src/main/java/com/studycollaboproject/scope/repository/BookmarkRepository.java
- src/main/java/com/studycollaboproject/scope/service/GithubUserService.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
북마크 삭제가 안되서 중복으로 값이 저장되고 있었다.
- 해결 완료
-
> [수정] 북마크 삭제 오류 수정

- scripts/profile.sh
- scripts/stop.sh
stop.sh IDLE_PROFILE->CONTAINER_ID 수정
- 
stop.sh IDLE_PROFILE->CONTAINER_ID 수정
-
> [수정] stop.sh IDLE_PROFILE->CONTAINER_ID 수정

- scripts/health.sh
- scripts/profile.sh
- scripts/start.sh
- scripts/stop.sh
Fix inability to switch 'IDLE_PROFILE' state from shellfile
- 
-
> [수정] Switch / Start 쉘파일 수정

- src/main/java/com/studycollaboproject/scope/config/OpenApiConfig.java
- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/ApplicantRestController.java
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/dto/PostDetailDto.java
- src/main/java/com/studycollaboproject/scope/dto/ResponseDto.java
- src/main/java/com/studycollaboproject/scope/model/User.java
- src/main/java/com/studycollaboproject/scope/security/JwtAuthenticationFilter.java
- src/main/java/com/studycollaboproject/scope/service/GithubUserService.java
- src/main/java/com/studycollaboproject/scope/service/KakaoUserService.java
ResponseDto 변경
- ResponseDto status 제거
-
> [수정] ResponseDto 변경

- src/main/java/com/studycollaboproject/scope/ScopeApplication.java
- src/main/java/com/studycollaboproject/scope/controller/ApplicantRestController.java
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/SnsLoginRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserInfoRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/dto/MemberListResponseDto.java
- src/main/java/com/studycollaboproject/scope/exception/RestApiExceptionHandler.java
- src/main/java/com/studycollaboproject/scope/model/Team.java
- src/main/java/com/studycollaboproject/scope/security/ExceptionHandlerFilter.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
- src/main/java/com/studycollaboproject/scope/service/GithubUserService.java
- src/main/java/com/studycollaboproject/scope/service/KakaoUserService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
Response 수정
- ResponseDto 의 status 항목 삭제
-
> [수정] Response 수정

- .github/workflows/gradle.yml
- Dockerfile
- build.gradle
- docker-compose.yml
- scripts/start.sh
- scripts/stop.sh
- src/main/java/com/studycollaboproject/scope/ScopeApplication.java
- src/main/java/com/studycollaboproject/scope/security/JasyptConfig.java
- src/main/resources/application-real1.properties
- src/main/resources/application-real2.properties
- src/main/resources/application.properties
Properties 암호화를 위한 JasyptConfig 구현 및 쉘스크립트/워크플로우 수정
- Jasypt Config Class 작성 / Git Seceret을 이용한 Codedeploy 수정 및 쉘스크립트  Docker run 수정
-
> [추가] Properties 암호화를 위한 JasyptConfig 구현 및 쉘스크립트/워크플로우 수정

- src/main/java/com/studycollaboproject/scope/service/GithubUserService.java
- src/main/java/com/studycollaboproject/scope/service/KakaoUserService.java
> [수정] SNS 로그인 수정

- src/main/java/com/studycollaboproject/scope/model/TotalResult.java
- src/main/java/com/studycollaboproject/scope/service/GithubUserService.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
추천 결과물 조회 시 자신이 선호하는 성향이 먼저 보이도록 수정
- 기존 가중치 로직 주석처리 후 추천 성향 리스트 가장 앞에 자신이 선호하는 성향을 넣음
-
> [추가] 추천 결과물 조회 시 자신이 선호하는 성향이 먼저 보이도록 수정

- build.gradle
- src/main/java/com/studycollaboproject/scope/dto/PostRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/UserResponseDto.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
- src/main/java/com/studycollaboproject/scope/model/Team.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepository.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
- src/main/java/com/studycollaboproject/scope/util/AspectTime.java
'YYYY-MM-DD' 타입과 UTC 시간 타입을 모두 수용할 수 있도록 변경
- PostRequestDto, Post 내용 수정
-
> [수정] Post 작성및 수정 시 날짜를 String으로 받도록 변경

- src/main/java/com/studycollaboproject/scope/model/Post.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepository.java
- src/main/java/com/studycollaboproject/scope/repository/TechStackRepository.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/TestService.java
성향 타입 추가, 추천 로직 변경
- R타입 추가
- 게시글 조회 중복 제거
- 조회 로직 수정
-
> [수정] 성향 타입 추가, 추천 로직 변경

- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/dto/MypageResponseDto.java
- src/main/java/com/studycollaboproject/scope/dto/UserResponseDto.java
- src/main/java/com/studycollaboproject/scope/model/User.java
마이페이지 조회 수정
- boolean -> Boolean
- userDetails에 null이 들어왔을 때 예외처리
> [수정] boolean -> Boolean

- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/ApplicantRestController.java
- src/main/java/com/studycollaboproject/scope/controller/AssessmentRestController.java
- src/main/java/com/studycollaboproject/scope/controller/ImageRestController.java
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserInfoRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/exception/BadRequestException.java
- src/main/java/com/studycollaboproject/scope/exception/ForbiddenException.java
- src/main/java/com/studycollaboproject/scope/exception/NoAuthException.java
- src/main/java/com/studycollaboproject/scope/exception/RestApiException.java
- src/main/java/com/studycollaboproject/scope/exception/RestApiExceptionHandler.java
- src/main/java/com/studycollaboproject/scope/model/User.java
- src/main/java/com/studycollaboproject/scope/security/JwtTokenProvider.java
- src/main/java/com/studycollaboproject/scope/service/ApplicantService.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
- src/main/java/com/studycollaboproject/scope/service/ImageService.java
- src/main/java/com/studycollaboproject/scope/service/MailService.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/TeamService.java
- src/main/java/com/studycollaboproject/scope/service/TestService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
에러타입 세분화
- 로그인 필요, 권한 필요, 요청 불량 에러로 세분화
-
> [수정] 에러타입 세분화 수정

- src/main/java/com/studycollaboproject/scope/config/WebSecurityConfig.java
- src/main/java/com/studycollaboproject/scope/controller/AssessmentRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/model/ProjectStatus.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/MailService.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/resources/application.properties
부하 테스트용 더미 데이터 10000개 추가
- testDataRunner 수정
-
> [수정] 부하테스트용 더미 추가

- src/main/java/com/studycollaboproject/scope/config/AsyncConfig.java
- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/ApplicantRestController.java
- src/main/java/com/studycollaboproject/scope/service/MailService.java
메일 전송 비동기처리
-  비동기 처리를 위한 config 파일 추가
- mailService에 비동기처리 (Async)
- 메일 전송 확인 log 추가
-
> [추가] 메일 전송 비동기처리

- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/exception/ErrorCode.java
- src/main/java/com/studycollaboproject/scope/model/Team.java
- src/main/java/com/studycollaboproject/scope/security/JwtTokenProvider.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
- src/main/java/com/studycollaboproject/scope/service/TeamService.java
팀원 평가 로직 수정
- 팀장이 팀원 평가 완료시 프로젝트 종료.
-
> [수정] 팀원 평가 로직 수정

- src/main/resources/application-real1.properties
- src/main/resources/application-real2.properties
> [수정] kakao 배포 -> 로컬

- src/main/java/com/studycollaboproject/scope/controller/ApplicantRestController.java
- src/main/java/com/studycollaboproject/scope/controller/AssessmentRestController.java
- src/main/java/com/studycollaboproject/scope/controller/ImageRestController.java
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/SnsLoginRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TestDataRunner.java
- src/main/java/com/studycollaboproject/scope/controller/TestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserInfoRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/filter/JwtAuthenticationFilter.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
- src/main/java/com/studycollaboproject/scope/model/Team.java
- src/main/java/com/studycollaboproject/scope/security/JwtTokenProvider.java
- src/main/java/com/studycollaboproject/scope/security/UserDetailsServiceImpl.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/TeamService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
- src/main/java/com/studycollaboproject/scope/util/AspectTime.java
> [수정] 로그 수정

- src/main/java/com/studycollaboproject/scope/dto/PostRequestDto.java
- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/filter/ExceptionHandlerFilter.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
timestamp 설정, 용량 설정 에러 수정
- 게시글 작성 및 수정 시 timestamp로 받도록 변경
- 용량 설정 10kb 를 10mb 로 수정
-
> [수정] timestamp 설정, 용량 설정 에러 수정

- src/main/java/com/studycollaboproject/scope/service/UserService.java
탈퇴한 유저의 포스트의 상태를 판단하여 종료한 포스트가 아니면 삭제
- 탈퇴한 유저의 포스트의 상태를 판단하여 종료한 포스트가 아니면 삭제
-
> [수정] 탈퇴 유저 포스트 관리

- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtensionImpl.java
프로젝트 조회 query 변경
- 마감 프로젝트 조회시 현재 날짜 기준으로 조회
- 모집중, 진행중 프로젝트만 조회
-
> [수정] 프로젝트 조회 query 변경

- src/main/java/com/studycollaboproject/scope/service/UserService.java
회원 탈퇴시 post에 있는 techstack 삭제
- 회원 탈퇴시 post에 있는 techstack 삭제
-
> [수정] 탈퇴 유저 포스트 연관관계 관련 이슈 수정

- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
프로젝트 최신순 조회 시 수정날짜 기준으로 조회하도록 수정
- 수정날짜 기준으로 정렬하여 조회하도록 수정
-
> [수정] 프로젝트 최신순 조회 수정

- src/main/java/com/studycollaboproject/scope/service/UserService.java
탈퇴시 유저가 맴버로 속해있는 팀의 총 인원수 -1
- UserService의 deleteUser 수정
-
> [수정] 팀에 탈퇴한 유저가 있을 때 총 인원수 -1

- src/main/java/com/studycollaboproject/scope/repository/TeamRepository.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
프로젝트 종료 메일 로직 수정
- 전체 팀맴버에게 메일 발송하도록 변경
-
> [수정] 프로젝트 종료 메일 로직 수정

- src/main/java/com/studycollaboproject/scope/controller/HomeController.java
HomeController 변경
- HomeController 변경
-
> [수정] HomeController 변경

- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
> [수정] CORS 설정

- src/main/java/com/studycollaboproject/scope/service/MailService.java
- src/main/resources/templates/acceptTeamEmail.html
- src/main/resources/templates/applicantEmail.html
- src/main/resources/templates/applicationNoticeEmail.html
> [수정] 이메일 수정

- src/main/java/com/studycollaboproject/scope/controller/HomeController.java
- src/main/resources/application-real1.properties
- src/main/resources/application-real2.properties
- src/main/resources/application.properties
Whitelabe false 설정 , server Url 추가
- properties 수정
-
> [수정] Whitelabe false 설정 , server Url 추가

- src/main/java/com/studycollaboproject/scope/controller/HomeController.java
HomeController 수정
- HomeController 수정
-
> [수정] HomeController 수정

- src/main/java/com/studycollaboproject/scope/config/OpenApiConfig.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepository.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/AssessmentService.java
- src/main/resources/application.properties
팀원 평가 종료 후 메일 전송되지 않는 에러 수정
- 메일 전송을 위한 유저 조회 로직 변경 
-
> [수정] 팀원 평가 종료 메일 전송 에러 수정

- src/main/resources/templates/responsePage.html
이메일 결과 페이지 추가
- responsePage.html 추가
-
> [추가] 이메일 결과 페이지 추가

- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
유저가 만든건지 아닌지 boolean으로 판단, 포스트 멤버들에 대한 정보 불러오기
- postservice, postcontroller 수정
-
> [수정] 유저가 만든건지 아닌지 boolean으로 판단, 포스트 멤버들에 대한 정보 불러오기

- src/main/java/com/studycollaboproject/scope/dto/MypageResponseDto.java
- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/PostRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
기술스택 필터링 제거, 마이페이지 Post조회 쿼리 수정
- Post 엔티티의 TeamList 를 List -> Set으로 변경
- 최신글 조회시 기술 스택으로 필터링 하여 조회하는 부분을 제거
- My페이지 TeamMember 조회 쿼리를 Post 조회시 한번에 조회하도록 변경
-
> [수정] 기술스택 필터링 제거, 마이페이지 Post조회 쿼리 수정

- src/main/java/com/studycollaboproject/scope/dto/SignupRequestDto.java
- src/main/java/com/studycollaboproject/scope/model/User.java
user entity 생성자 수정
- 생성자에 mailAuthenticationCode 빈 문자열 추가
-
> [수정] user entity 생성자 수정

- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
[수정] 포스트 멤버들에 대한 정보 / 평가정보 보내기
- PostResponseDto
-
> [수정] 포스트 멤버들에 대한 정보 / 평가정보 보내기

- src/main/java/com/studycollaboproject/scope/service/MailService.java
> [수정] 종료 메일 로직 수정

- src/main/java/com/studycollaboproject/scope/service/UserService.java
> [수정] save 디버깅

- src/main/java/com/studycollaboproject/scope/model/User.java
mailAuthenticationCode 수정
- mailAuthenticationCode 값 UUID 생성
-
> [수정] mailAuthenticationCode 수정

- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/exception/ErrorCode.java
- src/main/java/com/studycollaboproject/scope/repository/ApplicantRepository.java
- src/main/java/com/studycollaboproject/scope/repository/ApplicantRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/ApplicantRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/ApplicantService.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
- src/main/java/com/studycollaboproject/scope/service/TeamService.java
- src/main/java/com/studycollaboproject/scope/service/UserService.java
team 지원 시 중복 지원 수정
이미지 로드 경로 문제 해결
- 이미 member일 때 또 지원 되는 경우 수정
- 이미 member일때 member 승인 경우 수정
- images 경로 추가
- images, logs 해당 폴더가 존재하지 않을 시 생성하도록 수정
-
> [수정] team 지원 시 중복 지원 수정, 이미지 로드 문제 해결

- src/main/java/com/studycollaboproject/scope/ScopeApplication.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtension.java
- src/main/java/com/studycollaboproject/scope/repository/TeamRepositoryExtensionImpl.java
- src/main/java/com/studycollaboproject/scope/service/ApplicantService.java
- src/main/java/com/studycollaboproject/scope/service/TeamService.java
팀 지원, 팀 승낙 문제 해결
- 지원 현황 조회시 postId 로 where절 추가
-
> [수정] 팀 지원, 팀 승낙 문제 해결

- src/main/java/com/studycollaboproject/scope/service/PostService.java
> [수정] post 작성시 유효성검사 수정

- src/main/java/com/studycollaboproject/scope/dto/PostResponseDto.java
- src/main/java/com/studycollaboproject/scope/model/Post.java
마이페이지 기술스택 중복 수정
- Set을 techstack 으로 변경
-
> [수정] 마이페이지 기술스택 중복 수정

- src/main/java/com/studycollaboproject/scope/listener/SessionUserCounter.java
동시 접속자 수 확인 위한 로직 추가
- HttpSessionListener를 상속하는 SessionUserCounter 클래스 추가 
count 필드를 추가해서 동접자 수 count
- 현재는 동접자 수를 log에서만 확인 가능합니다!
> [추가] 동시 접속자 수 확인 위한 로직 추가

- logs/log-2021-11-30_0.log
- src/main/java/com/studycollaboproject/scope/config/WebConfig.java
- src/main/java/com/studycollaboproject/scope/ipfilter/HttpInterceptor.java
- src/main/java/com/studycollaboproject/scope/ipfilter/IpBanList.java
- src/main/java/com/studycollaboproject/scope/ipfilter/IpBanRepository.java
- src/main/java/com/studycollaboproject/scope/ipfilter/IpBanService.java
- src/main/java/com/studycollaboproject/scope/ipfilter/PricingPlanService.java
> [수정] Ipban 기능 추가

- README.md
> [수정] Readme 파일 수정

- .github/workflows/gradle.yml
- logs/log-2021-12-02_0.log
- scripts/health.sh
- src/main/java/com/studycollaboproject/scope/controller/PostRestController.java
- src/main/java/com/studycollaboproject/scope/controller/TeamRestController.java
- src/main/java/com/studycollaboproject/scope/controller/UserRestController.java
- src/main/java/com/studycollaboproject/scope/ipfilter/HttpInterceptor.java
- src/main/java/com/studycollaboproject/scope/ipfilter/IpBanService.java
- src/main/java/com/studycollaboproject/scope/ipfilter/PricingPlanService.java
- src/main/java/com/studycollaboproject/scope/service/PostService.java
[수정] main 빌드를 위한 workflow dev 삭제
- [수정] main 빌드를 위한 workflow dev 삭제
-
> [수정] main 빌드를 위한 workflow dev 삭제

- src/main/java/com/studycollaboproject/scope/service/PostService.java
cache 속도 측정시간 변경
- cache 속도 측정시간 변경
-
> [수정] cache 속도 측정시간 변경

- src/main/java/com/studycollaboproject/scope/controller/ApiTestRestController.java
> [수정] Test API 주석
